[project]
name = "polygon-clean-worker"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.worker-fund-manager]
path = "contracts/worker-fund-manager.clar"
depends_on = []

[contracts.worker-coordination]
path = "contracts/worker-coordination.clar"
depends_on = []

[contracts.worker-compensation]
path = "contracts/worker-compensation.clar"
depends_on = []

[contracts.worker-assignment]
path = "contracts/worker-assignment.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
